name: CI

on:
    push:
        branches: [ "master", "Action-Testing" ]
    pull_request:
        branches: [ "master", "Action-Testing" ]

    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v4
  
        -   name: Setup DepotDownloader
            run: |
                wget https://github.com/SteamRE/DepotDownloader/releases/download/DepotDownloader_2.5.0/DepotDownloader-linux-x64.zip
                unzip DepotDownloader-linux-x64.zip
                chmod +x DepotDownloader
        
        -   name: Download PlateUp
            uses: Wandalen/wretry.action@master
            env:
                USER: ${{ secrets.STEAM_USERNAME }}
                PASS: ${{ secrets.STEAM_PASSWORD }}
            with:
                command: ./DepotDownloader -app 1599600 -depot 1599601 -username "$USER" -password "$PASS"
                attempt_limit: 3
                attempt_delay: 2000
                
        -   name: Export PlateUp path
            id: gamepath
            run: |
                gamepath=`ls -d /home/runner/work/Yariazen.PlateUp.ModBuildUtilities/Yariazen.PlateUp.ModBuildUtilities/depots/1599601/**`/PlateUp
                echo "gamepath=$gamepath" >> $GITHUB_OUTPUT
        
        -   name: Install Debug Tools
            run: sudo apt install -y tree
    
        -   name: Install .NET Core
            uses: actions/setup-dotnet@v3
            with:
                dotnet-version: 6.x
        
        -   name: Build ModBuildUtilities
            run: |
                cd Yariazen.PlateUp.ModBuildUtilities
                dotnet build -c Release
                cd ..
        
        -   name: Build GenerateReferences
            run: |
                cd GenerateReferences
                dotnet nuget add source /home/runner/work/Yariazen.PlateUp.ModBuildUtilities/Yariazen.PlateUp.ModBuildUtilities/Yariazen.PlateUp.ModBuildUtilities/bin/Release
                dotnet add package Yariazen.PlateUp.ModBuildUtilities
                dotnet build -c Release -p:GamePath=`ls -d /home/runner/work/Yariazen.PlateUp.ModBuildUtilities/Yariazen.PlateUp.ModBuildUtilities/depots/1599601/**`/PlateUp -p:EnableGameDebugging='false'
                cd ..
                
        -   name: Docker Wine
            run: |
                wget https://raw.githubusercontent.com/scottyhardy/docker-wine/master/docker-wine
                chmod +x docker-wine
                
        -   name: Run PlateUp
            timeout-minutes: 1
            env:
                GAMEPATH: ${{ steps.gamepath.outputs.gamepath }}
            run: ./docker-wine --xvfb=:95,0,720x480x8 "$GAMEPATH"/PlateUp.exe
  
            
    #  - name: Install Refasmer
    #    run: dotnet tool install -g JetBrains.Refasmer.CliTool
            
    #  - name: Build Package
    #    run: dotnet build

    #  - name: Upload build artifacts
    #    uses: actions/upload-artifact@v4
    #    with:
    #      name: Yariazen.Plateup.ModBuildUtilities
    #      path: ./bin/Debug/Yariazen.PlateUp.ModBuildUtilities.*.nupkg
    #      if-no-files-found: error

    #  - name: Upload Release
    #    env:
    #      API_KEY: ${{secrets.PLATEUP_MODBUILDUTILITIES}}
    #    run: dotnet nuget push ./bin/Debug/Yariazen.PlateUp.ModBuildUtilities.1.13.0.nupkg --api-key "$API_KEY" --source https://api.nuget.org/v3/index.json
