name: CI

on:
    push:
        branches: [ "master", "Action-Testing" ]
    pull_request:
        branches: [ "master", "Action-Testing" ]

    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        -   uses: actions/checkout@v4
        
        -   name: Install Debug Tools
            run: |
                sudo apt install -y tree
                tree .

        -   name: Install X
            run: sudo apt install -y xvfb xdotool
    
        -   name: Install .NET Core
            uses: actions/setup-dotnet@v3
            with:
                dotnet-version: 6.x

        -   name: Build ModBuildUtilities
            run: |
                cd Yariazen.PlateUp.ModBuildUtilities
                dotnet build -c Release
                cd ..
        
        -   name: Build GenerateReferences
            run: |
                tree .
                cd GenerateReferences
                dotnet nuget add source /home/runner/work/Yariazen.PlateUp.ModBuildUtilities/Yariazen.PlateUp.ModBuildUtilities/bin/Release
                echo "Added source"
                [ -d "/home/runner/work/Yariazen.PlateUp.ModBuildUtilities/Yariazen.PlateUp.ModBuildUtilities/bin/Release" ] && echo "Dir exists." || echo "Dir does not exist."
                dotnet add package Yariazen.PlateUp.ModBuildUtilities
                echo "Added package"
                cd ..
  
            
    #  - name: Install Refasmer
    #    run: dotnet tool install -g JetBrains.Refasmer.CliTool
            
    #  - name: Build Package
    #    run: dotnet build

    #  - name: Upload build artifacts
    #    uses: actions/upload-artifact@v4
    #    with:
    #      name: Yariazen.Plateup.ModBuildUtilities
    #      path: ./bin/Debug/Yariazen.PlateUp.ModBuildUtilities.*.nupkg
    #      if-no-files-found: error

    #  - name: Upload Release
    #    env:
    #      API_KEY: ${{secrets.PLATEUP_MODBUILDUTILITIES}}
    #    run: dotnet nuget push ./bin/Debug/Yariazen.PlateUp.ModBuildUtilities.1.13.0.nupkg --api-key "$API_KEY" --source https://api.nuget.org/v3/index.json
