name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            6.x
            
      - name: Build
        run: dotnet build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Yariazen.Plateup.ModBuildUtilities
          path: ./bin/Debug/Yariazen.PlateUp.ModBuildUtilities.*.nupkg
          if-no-files-found: error

      - name: Upload Release
        with: 
          API_KEY: ${{ secrets.PLATEUP_MODBUILDUTILITIES}}
        run: dotnet nuget push ./bin/Debug/Yariazen.PlateUp.ModBuildUtilities.1.13.0.nupkg --api-key "$API_KEY" --source https://api.nuget.org/v3/index.json
